# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-07 07:08
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PurchaseRequisition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequisitionitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
